version: '3'

services:
  squidguard:
    image: bandwith/squidguard-debian
    hostname: squidguard
    environment:
      - TZ=America/New_York
      # I want to use WPAD
      - WPAD_IP=172.16.150.11
      - WPAD_NOPROXY_NET=172.16.150.0
      - WPAD_NOPROXY_MASK=255.255.255.0
      # here I want to use blacklists from shallalist, which are license restricted especially for commercial use
      - UPDATE_BLACKLIST_URL=http://www.shallalist.de/Downloads/shallalist.tar.gz
      # I have some config files I want to overwrite
      # e.g. squidGuard.conf, wpad.dat and block.html:
      - SQUID_CONFIG_SOURCE=/custom-config
    ports:
      - "3128:3128"
      - "80:80"
    expose:
      - 3128
      - 80
    volumes:
      # please adapt this to your needs
      - ./myconfig:/custom-config
      - /var/log/squid

  elk:
    build: ./elk
    hostname: elk
    environment:
      - TZ=America/New_York
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5000:5000"
      - "5044:5044"
    # expose:
    #   - 5601
    #   - 9200
    #   - 5000
    #   - 5044

  filebeat:
    image: elastic/filebeat:7.6.2
    # build: ./filebeat
    hostname: filebeat
    command: filebeat -e -strict.perms=false
    environment:
      - TZ=America/New_York
      - KIBANA_HOST=elk
      - ELASTICSEARCH_HOSTS=elk
      # - ELASTICSEARCH_USERNAME
      # - ELASTICSEARCH_PASSWORD
      # - LOGSTASH_HOST=elk
      # - LOGSTASH_PORT=5000
    volumes: 
      - ./filebeat/my-config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on: 
      - elk
      - squidguard
    links:
      - elk
      - squidguard
    
volumes:
  squidguard:
