filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

filebeat.inputs:
  - type: log
    paths:
      - /var/log/squid/access.log
    input_type: log
    ignore_older: 24h
    scan_frequency: 5s
    document_type: squid

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

# output.elasticsearch:
#   hosts: ["<es_url>"]
#   username: "elastic"
#   password: "<password>"

setup.kibana:
  host: '${KIBANA_HOST:elk:5601}'

# output.logstash:
#   hosts: ['${LOGSTASH_HOST:elk:5044}']

logging.files:
  rotateeverybytes: 10485760 # = 10MB
